version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ccitation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/citation_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - REACT_APP_API_URL=http://app:3000 
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./frontend:/frontend

volumes:
  postgres-data: