version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: citation_tool
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/citation_tool
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"